/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DLTABgVmZI3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"

export function Landing() {
  return (
    <div className="w-full min-h-screen bg-background text-foreground">
      <header className="bg-primary text-primary-foreground py-4 px-6 md:px-12">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <ScissorsIcon className="w-8 h-8" />
            <h1 className="text-2xl font-bold">LuSpa</h1>
          </div>
          <nav className="hidden md:flex items-center gap-6">
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Servicios
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Sobre Nosotros
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Contacto
            </Link>
          </nav>
          <Dialog>
            <DialogTrigger asChild>
              <Button variant="outline" className="hidden md:inline-flex">
                Reservar Ahora
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px]">
              <DialogHeader>
                <DialogTitle>Reservar Cita</DialogTitle>
                <DialogDescription>Completa el siguiente formulario para reservar tu cita.</DialogDescription>
              </DialogHeader>
              <div className="grid gap-4 py-4">
                <div className="grid items-center grid-cols-4 gap-4">
                  <Label htmlFor="name" className="text-right">
                    Nombre
                  </Label>
                  <Input id="name" placeholder="Ingresa tu nombre" className="col-span-3" />
                </div>
                <div className="grid items-center grid-cols-4 gap-4">
                  <Label htmlFor="date" className="text-right">
                    Fecha
                  </Label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button variant="outline" className="flex-col items-start w-full h-auto col-span-3">
                        <span className="font-normal">Selecciona una fecha</span>
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="p-0 max-w-[276px]">
                      <Calendar />
                    </PopoverContent>
                  </Popover>
                </div>
                <div className="grid items-center grid-cols-4 gap-4">
                  <Label htmlFor="time" className="text-right">
                    Hora
                  </Label>
                  <Select className="col-span-3">
                    <SelectTrigger>
                      <SelectValue placeholder="Selecciona una hora" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="9:00 AM">9:00 AM</SelectItem>
                      <SelectItem value="10:00 AM">10:00 AM</SelectItem>
                      <SelectItem value="11:00 AM">11:00 AM</SelectItem>
                      <SelectItem value="12:00 PM">12:00 PM</SelectItem>
                      <SelectItem value="1:00 PM">1:00 PM</SelectItem>
                      <SelectItem value="2:00 PM">2:00 PM</SelectItem>
                      <SelectItem value="3:00 PM">3:00 PM</SelectItem>
                      <SelectItem value="4:00 PM">4:00 PM</SelectItem>
                      <SelectItem value="5:00 PM">5:00 PM</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <DialogFooter>
                <Button type="submit">Reservar</Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </header>
      <main>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6 grid md:grid-cols-2 gap-8 items-center">
            <div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Eleva tu Belleza en LuSpa</h2>
              <p className="mt-4 text-muted-foreground md:text-xl/relaxed">
                Experimenta el máximo lujo y mimarte en nuestro salón de belleza de última generación. Nuestro equipo de
                expertos estilistas y técnicos se dedica a brindar servicios personalizados y creativos que te harán
                sentir refrescado y radiante.
              </p>
              <div className="mt-6 flex flex-col gap-2 sm:flex-row">
                <Dialog>
                  <DialogTrigger asChild>
                    <Button>Reservar una Cita</Button>
                  </DialogTrigger>
                  <DialogContent className="sm:max-w-[425px]">
                    <DialogHeader>
                      <DialogTitle>Reservar Cita</DialogTitle>
                      <DialogDescription>Completa el siguiente formulario para reservar tu cita.</DialogDescription>
                    </DialogHeader>
                    <div className="grid gap-4 py-4">
                      <div className="grid items-center grid-cols-4 gap-4">
                        <Label htmlFor="name" className="text-right">
                          Nombre
                        </Label>
                        <Input id="name" placeholder="Ingresa tu nombre" className="col-span-3" />
                      </div>
                      <div className="grid items-center grid-cols-4 gap-4">
                        <Label htmlFor="date" className="text-right">
                          Fecha
                        </Label>
                        <Popover>
                          <PopoverTrigger asChild>
                            <Button variant="outline" className="flex-col items-start w-full h-auto col-span-3">
                              <span className="font-normal">Selecciona una fecha</span>
                            </Button>
                          </PopoverTrigger>
                          <PopoverContent className="p-0 max-w-[276px]">
                            <Calendar />
                          </PopoverContent>
                        </Popover>
                      </div>
                      <div className="grid items-center grid-cols-4 gap-4">
                        <Label htmlFor="time" className="text-right">
                          Hora
                        </Label>
                        <Select className="col-span-3">
                          <SelectTrigger>
                            <SelectValue placeholder="Selecciona una hora" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="9:00 AM">9:00 AM</SelectItem>
                            <SelectItem value="10:00 AM">10:00 AM</SelectItem>
                            <SelectItem value="11:00 AM">11:00 AM</SelectItem>
                            <SelectItem value="12:00 PM">12:00 PM</SelectItem>
                            <SelectItem value="1:00 PM">1:00 PM</SelectItem>
                            <SelectItem value="2:00 PM">2:00 PM</SelectItem>
                            <SelectItem value="3:00 PM">3:00 PM</SelectItem>
                            <SelectItem value="4:00 PM">4:00 PM</SelectItem>
                            <SelectItem value="5:00 PM">5:00 PM</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>
                    <DialogFooter>
                      <Button type="submit">Reservar</Button>
                    </DialogFooter>
                  </DialogContent>
                </Dialog>
                <Button variant="outline">Más Información</Button>
              </div>
            </div>
            <img src="/placeholder.svg" width={600} height={400} alt="LuSpa" className="rounded-xl object-cover" />
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container mx-auto px-4 md:px-6 grid md:grid-cols-2 gap-8 items-center">
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Manicura Artística"
              className="rounded-xl object-cover"
            />
            <div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Manicura Artística Innovadora
              </h2>
              <p className="mt-4 text-muted-foreground md:text-xl/relaxed">
                Nuestros talentosos técnicos de uñas se especializan en crear diseños de uñas únicos que son visualmente
                impresionantes y duraderos. Desde manicuras clásicas hasta arte de uñas intrincado, utilizamos los
                productos y técnicas de la más alta calidad para asegurarnos de que tus uñas se vean absolutamente
                perfectas.
              </p>
              <div className="mt-6">
                <Button>Explora los Servicios de Uñas</Button>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6 grid md:grid-cols-2 gap-8 items-center">
            <div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Cortes de Cabello Precisos y Tratamientos Restauradores
              </h2>
              <p className="mt-4 text-muted-foreground md:text-xl/relaxed">
                Nuestros experimentados estilistas son maestros en su oficio, ofreciendo cortes de cabello precisos y
                tratamientos de cabello personalizados que transformarán tu apariencia y dejarán tu cabello más
                saludable que nunca. Ya sea que busques un corte fresco, un color vibrante o un tratamiento de
                acondicionamiento profundo, te tenemos cubierto.
              </p>
              <div className="mt-6">
                <Button>Explora los Servicios de Cabello</Button>
              </div>
            </div>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Tratamientos de Cabello"
              className="rounded-xl object-cover"
            />
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-4 md:px-6">
        <div className="container mx-auto flex flex-col md:flex-row items-center justify-between">
          <div className="flex items-center gap-4">
            <ScissorsIcon className="w-6 h-6" />
            <span className="text-sm font-medium">LuSpa</span>
          </div>
          <nav className="flex items-center gap-4 mt-4 md:mt-0">
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Política de Privacidad
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Términos de Servicio
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Contáctanos
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function ScissorsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="6" cy="6" r="3" />
      <path d="M8.12 8.12 12 12" />
      <path d="M20 4 8.12 15.88" />
      <circle cx="6" cy="18" r="3" />
      <path d="M14.8 14.8 20 20" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
